### PR TITLE
fix: add common-constraints to docs requirements

### PR DESCRIPTION
**Pull request by jansenk**

### CODE REVIEW

**Review by schenedx — APPROVED** [review]
👍

**Comment by jansenk** [comment]
Also includes https://github.com/openedx/edx-submissions/pull/187

**Comment by jansenk** [comment]
Ignoring codecov. The changed lines were clearing pylint warnings. I don't care about coverage in this context

**Comment by jansenk** [comment]
Also ignoring commitlint. My bad

**Pull request merged**
