### PR TITLE
feat: add migrations check

### PR DESCRIPTION
**Pull request by nsprenkle**
## About

Adds a migrations check, mirrored after similar workflows in [edx-platform](https://github.com/openedx/edx-platform/blob/24dced20937034735ed52164589b2919265e0c1c/.github/workflows/migrations-check-mysql8.yml#L12), [edx-notes-api](https://github.com/openedx/edx-notes-api/blob/b3cea821eb4a060f4f48e32685fb001704efa5c6/.github/workflows/migrations-mysql8-check.yml#L12), and [edx-analytics-dashboard](https://github.com/openedx/edx-analytics-dashboard/blob/4da5008fe951cfb6a3e98ea76f5c0e26da714de1/.github/workflows/mysql-migrations.yml#L12), to name a few.

Migration check further modified (based on [this test](https://github.com/openedx/edx-platform/blob/aa7370c773dcd96850fbda8e4f6ad40950c10547/common/djangoapps/util/tests/test_db.py#L137)) to actually fail when there are missing migration files.

JIRA: https://2u-internal.atlassian.net/browse/AU-820

## Testing Instructions

- [x] Verify new step (`Migrations check on mysql8`) appears on PRs. Should fail if a migration fails or is missing for future PRs.

### CODE REVIEW

**Comment by jansenk** [comment]
I think that the check should be failing on this PR I made off of your branch: https://github.com/openedx/edx-submissions/pull/197/files

**Comment by jansenk** [comment]
Wow, it looks like those aren't actually doing that check, it's just a unit test that's running?

https://github.com/openedx/edx-platform/pull/32301

[check migrations](https://github.com/openedx/edx-platform/actions/runs/5072591060/jobs/9110485721?pr=32301) and [check migrations mysql8](https://github.com/openedx/edx-platform/actions/runs/5072591061/jobs/9110486038?pr=32301) both pass! it's [a unit test](https://github.com/openedx/edx-platform/actions/runs/5072591052/jobs/9110487350?pr=32301) that fails, [specifically this one](https://github.com/openedx/edx-platform/blob/7b91f8579f5d6ebd9529a5c7f8bdb5578f40e7ea/common/djangoapps/util/tests/test_db.py#L124).

**Comment by nsprenkle** [comment]
> Wow, it looks like those aren't actually doing that check, it's just a unit test that's running?
> 
> [openedx/edx-platform#32301](https://github.com/openedx/edx-platform/pull/32301)
> 
> [check migrations](https://github.com/openedx/edx-platform/actions/runs/5072591060/jobs/9110485721?pr=32301) and [check migrations mysql8](https://github.com/openedx/edx-platform/actions/runs/5072591061/jobs/9110486038?pr=32301) both pass! it's [a unit test](https://github.com/openedx/edx-platform/actions/runs/5072591052/jobs/9110487350?pr=32301) that fails, [specifically this one](https://github.com/openedx/edx-platform/blob/7b91f8579f5d6ebd9529a5c7f8bdb5578f40e7ea/common/djangoapps/util/tests/test_db.py#L124).

Is that to say we should be doing that as a unit test, as in `edx-platform`? I'm happy to do it that way instead, but am just making educated guesses at this time.

**Review by jansenk — APPROVED** [review]
the test fails on my test branch! looks great
https://github.com/openedx/edx-submissions/actions/runs/5083648614/jobs/9134917710?pr=197

**Pull request merged**
